obj-$(CONFIG_HUAWEI_SENSORS)				+= sensor/
obj-$(CONFIG_HUAWEI_TOUCH_SCREEN)			+= touchscreen/
obj-y			+= power/
obj-$(CONFIG_KRETPROBES) += rphone/
obj-y   += antenna_board_match/
obj-$(CONFIG_HW_DEVICE_DETECT)   += hw_devices/
